# Defines a system service for the Play application.
# Assumes a working Play deployment (via pvm: https://github.com/kaiinkinen/pvm) and Git are available, such as performed by the playEnv.yaml script.
# Run with: run -vv playService
---
- hosts: playServers.domains
  sudo: yes
  vars:
  - ubuntu_release: $ENV(ANSIBLE_UBUNTU_RELEASE)
  - user: $ENV(ANSIBLE_USER_ID)
  - group: $ENV(ANSIBLE_USER_ID)
  - home: /home/$user
  - repo_url: $ENV(ANSIBLE_REPO_URL)
  - repo_remote: origin
  - repo_version: master
  - play_version: $ENV(ANSIBLE_PLAY_VERSION)
  - pvm_path: $home/pvm/install/$play_version
  - dest: $home/projectClone
  - project_version: $ENV(ANSIBLE_PLAY_APP_VERSION)
  - project: $ENV(ANSIBLE_PLAY_APP_NAME)-$project_version

  tasks:
   - name: Copy Play service wrapper and point it to the Play app launch script
     action: copy src=../bin/remote/play dest=/etc/init.d/play force=yes

   - name: Patch play service script
     lineinfile: dest=/etc/init.d/play regexp=PLAY_APP_SCRIPT line='        $home/$project/bin/$ENV(ANSIBLE_PLAY_APP_NAME) \\\'
